// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// categories.js
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE'

// sharings.js
export const FETCH_SHARINGS_SUCCESS = 'FETCH_SHARINGS_SUCCESS'
export const FETCH_SHARINGS_FAILURE = 'FETCH_SHARINGS_FAILURE'
export const FETCH_SHARING_SUCCESS = 'FETCH_SHARING_SUCCESS'
export const FETCH_SHARING_FAILURE = 'FETCH_SHARING_FAILURE'
export const FETCH_SHARING_REQUESTS_SUCCESS = 'FETCH_SHARING_REQUESTS_SUCCESS'
export const FETCH_SHARING_REQUESTS_FAILURE = 'FETCH_SHARING_REQUESTS_FAILURE'
export const SYNC_SHARINGS = 'SYNC_SHARINGS'
export const UPDATE_SHARING = 'UPDATE_SHARING'
// lang.js
export const SET_LOCALE = 'SET_LOCALE'
