// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// settings.js
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS'
export const FETCH_TRANSACTIONS_FAILURE = 'FETCH_TRANSACTIONS_FAILURE'
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS'
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE'
export const FETCH_READ_NOTIFICATIONS_SUCCESS = 'FETCH_READ_NOTIFICATIONS_SUCCESS'
export const FETCH_READ_NOTIFICATIONS_FAILURE = 'FETCH_READ_NOTIFICATIONS_FAILURE'

// stripe.js
export const FETCH_STRIPE_PAYMENTMETHODS_SUCCESS = 'FETCH_STRIPE_PAYMENTMETHODS_SUCCESS'
export const FETCH_STRIPE_PAYMENTMETHODS_FAILURE = 'FETCH_STRIPE_PAYMENTMETHODS_FAILURE'
export const ADD_STRIPE_PAYMENTMETHOD_SUCCESS = 'ADD_STRIPE_PAYMENTMETHOD_SUCCESS'
export const ADD_STRIPE_PAYMENTMETHOD_FAILURE = 'ADD_STRIPE_PAYMENTMETHOD_FAILURE'
export const REMOVE_STRIPE_PAYMENTMETHOD_SUCCESS = 'REMOVE_STRIPE_PAYMENTMETHOD_SUCCESS'
export const REMOVE_STRIPE_PAYMENTMETHOD_FAILURE = 'REMOVE_STRIPE_PAYMENTMETHOD_FAILURE'
export const UPDATE_STRIPE_PAYMENTDEFAULTMETHOD_SUCCESS = 'UPDATE_STRIPE_PAYMENTDEFAULTMETHOD_SUCCESS'
export const UPDATE_STRIPE_PAYMENTDEFAULTMETHOD_FAILURE = 'UPDATE_STRIPE_PAYMENTDEFAULTMETHOD_FAILURE'

// categories.js
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE'

// sharings.js
export const FETCH_SHARINGS_SUCCESS = 'FETCH_SHARINGS_SUCCESS'
export const FETCH_SHARINGS_FAILURE = 'FETCH_SHARINGS_FAILURE'
export const FETCH_SHARING_SUCCESS = 'FETCH_SHARING_SUCCESS'
export const FETCH_SHARING_FAILURE = 'FETCH_SHARING_FAILURE'
export const FETCH_CHATS_SUCCESS = 'FETCH_SHARING_CHATS_SUCCESS'
export const FETCH_CHATS_FAILURE = 'FETCH_SHARING_CHATS_FAILURE'
export const SYNC_SHARINGS = 'SYNC_SHARINGS'
export const UPDATE_SHARING = 'UPDATE_SHARING'
export const FETCH_CREDENTIALS_SUCCESS = 'FETCH_CREDENTIALS_SUCCESS'
export const FETCH_CREDENTIALS_FAILURE = 'FETCH_CREDENTIALS_FAILURE'
export const SAVE_CREDENTIALS_SUCCESS = 'SAVE_CREDENTIALS_SUCCESS'
// lang.js
export const SET_LOCALE = 'SET_LOCALE'
export const SET_COUNTRY = 'SET_COUNTRY'
